### ISSUE TITLE
need updates

### ISSUE THREAD

**Issue by DisableAsync** [DevilWithin/Nephilim#2]
i tried it on windows, and encountered lots of header file missing errors.
and i cant find matching files for some of them.

**Comment by eXpl0it3r** [comment]
The last update was over 2 years ago. Chances are the engine has been discontinued.

If you want a stable and proven engine, you could check out: https://godotengine.org

**Comment by DisableAsync** [comment]
@eXpl0it3r Godot looks good, but i hate its script, i want pure cpp <3

**Comment by eXpl0it3r** [comment]
Doesn't Godot allow you to write everything in C++? But honestly, you aren't doing yourself any favors by wanting to do everything in C++. 😉

**Comment by DisableAsync** [comment]
It doesnt provide docs for that :) thats real newbie-friendly

**Comment by DisableAsync** [comment]
@eXpl0it3r little funny question here: why are you watching this?

**Comment by eXpl0it3r** [comment]
So you want newbie friendly docs for hardcore C++ deving when there is a newbie friendly scripting language for Godot, asked on an issue tracker for an outdated engine with little to no documentation? 🤔😀

I used to talk to the dev of the engine quite a bit. Guess I watched the repo back then. Didn't even remember I still was watching​ it.

Hiw did you find it?

**Comment by DisableAsync** [comment]
@eXpl0it3r  i spent weeks finding a easy to use,opensource, lightweight, commercial-friendly licenced C++ 3D game engine, and last night i found [one topic on sfml forum](https://en.sfml-dev.org/forums/index.php?topic=14690.0), then i saw Grimshaw's signature 
:) that's it, sorry for my weak english and weird expression.

**Comment by DisableAsync** [comment]
@eXpl0it3r you are on the SFML team? why would you recommend me Godot?

**Comment by eXpl0it3r** [comment]
Ah okay.

Yes, I'm part of the SFML Team and I recommended Godot because you were looking for an engine and not a C++ library on top of which engines can potentially be built. 😉

**Comment by DisableAsync** [comment]
@eXpl0it3r can you give me other suggestions? xD

**Comment by eXpl0it3r** [comment]
Not really, I haven't done any work in that direction.

Maybe bgfx could be useful for you? https://github.com/bkaradzic/bgfx
Otherwise there's like Urho3d which is inspired by OGRE and Horde3D: https://github.com/urho3d/Urho3D
And then there are of course random lists that you can find on the internet: https://gamedev.stackexchange.com/questions/21/easy-to-use-cross-platform-3d-engines-for-c-game-development

**Comment by DisableAsync** [comment]
@eXpl0it3r Great minds think alike. (Joking, I don't have a great mind. xD)
I had started looking into Urho3D again last night. This time things going well.

**Comment by GrimshawA** [comment]
Hi Guys, I probably should have left a big disclaimer but this repository is not maintained in github anymore, and its been years since I changed.

The engine is maintained in a private repository at this moment, still under active development and looks nothing like it was at this point 

Cheers :)

**Comment by JymWythawhy** [comment]
Good to hear it is still under development- could you post something here when you release it to the public (if you are planning on doing so)?

**Comment by DisableAsync** [comment]
It's always good to hear these awesome project still being developed. Though I've decided to look into Urho3D.
